// GLOBAL TYPE
export const TOGGLE_MENU_DASHBOARD = "TOGGLE_MENU_DASHBOARD";
export const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR";
export const WITHOUT_LAYOUT = "WITHOUT_LAYOUT";
export const TOGGLE_IS_LOADING = "TOGGLE_IS_LOADING";
export const TOGGLE_LANGUAGE = "TOGGLE_LANGUAGE";
export const TOGGLE_DIALOG = "TOGGLE_DIALOG";
// GLOBAL TYPE

