export const STRATEGY_BUILT = "STRATEGY_BUILT";
export const UPDATE_TIME_FRAME = "UPDATE_TIME_FRAME";
export const UPDATE_PARAMETERS = "UPDATE_PARAMETERS";
export const SET_INDICATOR = "SET_INDICATOR";
export const UPDATE_CROSS_SIDE = "UPDATE_CROSS_SIDE";
export const UPDATE_CROSS_OFFSET = "UPDATE_CROSS_OFFSET";
export const TOGGLE_CROSS_STATUS = "TOGGLE_CROSS_STATUS";
export const TOGGLE_BREAKE_STATUS = "TOGGLE_BREAKE_STATUS";
export const UPDATE_BREAKE_CROSSING_LINE = "UPDATE_BREAKE_CROSSING_LINE";
export const UPDATE_CROSS_CROSSING_LINE = "UPDATE_CROSS_CROSSING_LINE";
export const UPDATE_BREAKE_OFFSET = "UPDATE_BREAKE_OFFSET";
export const UPDATE_BREAKE_SIDE = "UPDATE_BREAKE_SIDE";
export const UPDATE_BREAKE_TYPE = "UPDATE_BREAKE_TYPE";
export const UPDATE_BREAKE_VALUE = "UPDATE_BREAKE_VALUE";
export const SET_COMBINE_INDICATOR_ID = "SET_COMBINE_INDICATOR_ID";
export const BUILT_COMBINE = "BUILT_COMBINE";
export const UPDATE_COMBINE_INDICATOR_OFFSET =
  "UPDATE_COMBINE_INDICATOR_OFFSET";
export const UPDATE_COMBINE_INDICATOR_PARAMETER =
  "UPDATE_COMBINE_INDICATOR_PARAMETER";
export const SET_COMBINE_INDICATOR = "SET_COMBINE_INDICATOR";
export const UPDATE_COMBINE_INDICATOR_SIDE = "UPDATE_COMBINE_INDICATOR_SIDE";
export const SET_LIMIT_TYPE = "SET_LIMIT_TYPE";
export const SET_LIMIT_VALUE = "SET_LIMIT_VALUE";
export const SET_SETTINGS = "SET_SETTINGS";
export const CLEAN_UP = "CLEAN_UP"
export const UPDATE_CHART_TYPE = "UPDATE_CHART_TYPE"